### ISSUE TITLE
Food inventory Arrives and scanned into system

### ISSUE THREAD

**Issue by komizutama** [openpantry/open_pantry#43]
- [ ] Barcode of package scanned
- [ ] Check's UPC/USDA db for presence of item. 
- [ ] If not present, requests information regarding, item, package size and classification (if known)
- [ ] If present updates database with quantity.
- [ ] Returns positive confirmation.
